### ISSUE TITLE
tf-apko and apko produce diff results with single arch

### ISSUE THREAD

**Issue by mattmoor** [chainguard-dev/terraform-provider-apko#172]
When an image specifies `archs: [amd64]` (any singleton) `apko` produces an index with the single architecture, and tf-apko produces just the image.

For our reproducibility checks to hold we need these to be consistent.

**Comment by mattmoor** [comment]
cc @vaikas

**Comment by jonjohnsonjr** [comment]
https://github.com/chainguard-dev/terraform-provider-apko/pull/173
